astra_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("shopping_cart.urls", namespace="cart")),
    path("user_cabinet/", include("user_cabinet.urls")),
    path("", include("main_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path

from main_app.views import main_page, Catalog, Category, ProductSingle, about

urlpatterns = [
    path("", main_page, name="main_page"),
    path("catalog/", Catalog.as_view(), name="catalog"),
    path("category/<int:category_id>", Category.as_view(), name="category"),
    path("product/<int:product_id>", ProductSingle.as_view(), name="product"),
    path("about", about, name="about"),
]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
    path("create_order", views.create_order, name="create_order"),
]

templates/cart/cart_detail.html
{% extends "main_app/base.html" %}
{% load static %}
{% load mathfilters %}

{% block body_title %}Оформление заказа{% endblock %}

{% block body_content %}
<div class="row g-1">
  <div class="order-md-last">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-primary">Ваша корзина</span>
      <span class="badge bg-primary rounded-pill">{{ cart.get_total_quantities }}</span>
    </h4>
  {% if cart.get_total_quantities != 0 %}
   <ul class="list-group mb-3">
        {% for item in cart %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0"><a class="text-primary" href="{% url "product" product_id=item.product.pk %}">{{ item.product.name.capitalize}}</a></h6>
            </div>
            <span class="text-muted">{{ item.product.price }}₽</span>
            <div>
                <form action="{% url 'cart:cart_add' item.product.pk %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }} шт. {{ item.update_quantity_form.update }}
                    <input class="btn btn-dark " type="submit" value="Изменить">
                </form>
            </div>
              <form action="{% url 'cart:cart_remove' item.product.pk %}">
                 <input class="btn btn-outline" type="submit" value="Удалить"><i class="fa-solid fa-trash"></i>
              </form>
              <span class="text-muted">{{ item.quantity|mul:item.product.price }}₽</span>
          </li>
        {% endfor %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
              <p class="h6">ИТОГО</p>
              <p class="text-bold">{{ cart.get_total_price }}₽</p>
          </li>
    </ul>
          <div class="container d-flex align-items-center">
              <form class="w-100" action="{% url "cart:create_order" %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="w-75 btn btn-dark btn-lg">Оформить заказ</button>
                  <a href="{% url "catalog" %}" class="btn btn-secondary btn-lg">В каталог</a>
              </form>
          </div>
      </div>
  {% else %}
      <p class="h3">Ваша корзина пуста! Добавьте товар в корзину и он появится здесь! </p>
  {% endif %}

</div>
{% endblock %}