astra_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("shopping_cart.urls", namespace="cart")),
    path("user_cabinet/", include("user_cabinet.urls")),
    path("", include("main_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path

from main_app.views import main_page, Catalog, Category, ProductSingle, about

urlpatterns = [
    path("", main_page, name="main_page"),
    path("catalog/", Catalog.as_view(), name="catalog"),
    path("category/<int:category_id>", Category.as_view(), name="category"),
    path("product/<int:product_id>", ProductSingle.as_view(), name="product"),
    path("about", about, name="about"),
]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
    path("create_order", views.create_order, name="create_order"),
]

main_app/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

from astra_shop.settings import MEDIA_ROOT


class ProductCategory(models.Model):
    """
    Класс, описывающий модель представления сущности "Категория продукта".

    Параметры:
        name -- наименование категории товара
        description -- краткое описание категории
        image -- фотография
    """

    name = models.CharField(max_length=255, blank=False)
    description = models.CharField(max_length=255, blank=False)
    image = models.ImageField(upload_to=MEDIA_ROOT)

    class Meta:
        verbose_name_plural = "Категории товара"

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    """
    Класс, описывающий модель представления сущности "Продукт".

    Параметры:
        name -- наименование товара
        description -- краткое описание товара
        category -- ссылка на категорию, к которой относится
        товар
        image -- фотография
        price -- стоимость одной единицы товара
    """

    name = models.CharField(max_length=255, blank=False)
    description = models.CharField(max_length=255, blank=False)
    category = models.ForeignKey(
        to="ProductCategory", on_delete=models.CASCADE, blank=False
    )
    image = models.ImageField(upload_to=MEDIA_ROOT)
    price = models.IntegerField(blank=False, default=0)

    def __str__(self):
        return f"{self.name} {self.category.name}"

    class Meta:
        verbose_name_plural = "Товары"


class Order(models.Model):
    """
    Класс, описывающий модель представления сущности "Заказ".

    Параметры:
        timestamp -- дата оформления заказа
        product -- ссылка на товар
        customer -- ссылка на пользователя, которым совершен заказ
    """

    timestamp = models.DateTimeField(
        blank=False,
    )
    customer = models.ForeignKey(
        to="user_cabinet.User", blank=False, on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.timestamp}, order #{self.pk} from {self.customer.first_name}"

    class Meta:
        verbose_name_plural = "Заказы"


class ProductsInOrder(models.Model):
    """
    Класс, описывающий модель представления сущности "Товары в заказах".
    Параметры:
        order -- ссылка на заказ
        product -- ссылка на товар
        quantity -- к-во товара в заказе
    """

    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()

    class Meta:
        verbose_name_plural = "Товары в заказах"


class CallBackOrder(models.Model):
    """
    Класс, описывающий модель представления сущности "Заявка на обратный звонок".
    Таблица хранит заявки от анонимных пользователей
    Параметры:
        name, email, phone_number -- контактные данные
        timestamp -- дата оформления заявки, по умолчанию - текущая дата
        comment -- комментарий к заявке
    """

    name = models.CharField(max_length=255, blank=False)
    email = models.CharField(max_length=255, blank=False)
    phone_number = models.CharField(max_length=255, blank=True, null=True)
    timestamp = models.DateTimeField(
        blank=False,
    )
    comment = models.CharField(max_length=255, blank=False)

    class Meta:
        verbose_name_plural = "Заявки на обратный звонок"

main_app/forms.py
import django.forms as forms


class CallBackOrderForUnauthorizedUsers(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Олег"}),
        max_length=30,
        required=True,
        label="Ваше имя:",
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={"placeholder": "oleg@mail.ru"}),
        required=True,
        label="Ваш e-mail:",
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "+7(312)123-12-12",
            }
        ),
        max_length=17,
        required=False,
        label="Ваш номер телефона (необязательно):",
    )
    comment = forms.CharField(
        max_length=350,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Ваш комментарий к заявке здесь...",
                "rows": "3",
            }
        ),
        label="Комментарий:",
        required=False,
    )
    preferred_communication_method = forms.CharField(
        required=False,
        label="Предпочитаемый способ связи",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Например, WhatsApp, после 17:00",
            }
        ),
    )


class CallBackOrderForAuthorizedUsers(forms.Form):
    """ """

    comment = forms.CharField(
        max_length=350,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Ваш комментарий к заявке здесь...",
                "rows": "3",
            }
        ),
        label="Комментарий:",
        required=False,
    )
    preferred_communication_method = forms.CharField(
        required=False,
        label="Предпочитаемый способ связи",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Например, WhatsApp, после 17:00",
            }
        ),
    )

main_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from main_app.forms import *
from main_app.models import *
from main_app.utils import *
from shopping_cart.forms import CartAddProductForm

add_to_cart_form = CartAddProductForm()


def main_page(request):
    """Отображает главную страницу"""
    context_data = {"title": "Главная"}
    return render(request, "main_app/main_page.html", context=context_data)


class Catalog(ListView):
    """
    Представление хранимых в БД категорий товара позволяющее при помощи
    встроенного в django шаблонизатора формировать шаблон динамически,
    основываясь на содержимом БД.

    model -- модель из main_app/models.py, на основе которой
    будет изменяться шаблон
    template_name -- предварительно созданный шаблон в templates/main_app
    extra_context -- дополнительные данные, отправляемых шаблонизатору
    """

    model = ProductCategory
    template_name = "main_app/catalog.html"
    extra_context = {"title": "Каталог товаров"}


class Category(ListView):
    """
    Представление хранимых в БД товаров, принадлежащих категории, которая
    будет выбрана на странице для детального ознакомления. Позволяет при помощи
    встроенного в django шаблонизатора формировать шаблон динамически,
    основываясь на содержимом БД.

    model -- модель из main_app/models.py, на основе которой
    будет изменяться шаблон
    template_name -- предварительно созданный шаблон в templates/main_app
    extra_context -- дополнительные данные, отправляемых шаблонизатору
    """

    model = Product
    template_name = "main_app/category_single.html"
    extra_context = {"menu": menu, "title": ""}

    def get_queryset(self):
        title = (
            ProductCategory.objects.filter(id=self.kwargs["category_id"])
            .first()
            .name.capitalize()
        )
        self.extra_context["title"] = title
        return Product.objects.filter(category=self.kwargs["category_id"])


class ProductSingle(DetailView):
    """
    Представление хранимых в БД данных о конкретном товаре. Позволяет
    при помощи встроенного в django шаблонизатора формировать шаблон
    динамически, основываясь на содержимом БД.

    model -- модель из main_app/models.py, на основе которой
    будет изменяться шаблон
    slug_field -- поле, по которому осуществляется перееход к DetailView
    нужной записи в таблице "Product"
    template_name -- предварительно созданный шаблон в templates/main_app
    extra_context -- дополнительные данные, отправляемых шаблонизатору
    """

    model = Product  # используемая таблица в БД
    slug_field = "pk"
    template_name = "main_app/product_single.html"
    extra_context = {"title": "", "add_to_cart_form": add_to_cart_form}

    def get_object(self, queryset=None):
        showed_object = self.model.objects.get(pk=self.kwargs["product_id"])
        self.extra_context["title"] = showed_object.name.capitalize()
        return showed_object


def about(request):
    """
    Отображает страницу с контактной информацией
    """
    user_is_authorized = request.user.is_authenticated
    form = (
        CallBackOrderForAuthorizedUsers(request.POST)
        if user_is_authorized
        else CallBackOrderForUnauthorizedUsers(request.POST)
    )
    if form.is_valid():
        # если данные в форме верны
        form_data: dict = form.cleaned_data
        call_back_order = CallBackOrder()
        if user_is_authorized:
            # Если пользователь авторизован
            phone_number_from_db = (
                request.user.phone_number
            )
            call_back_order.name = request.user.first_name
            call_back_order.email = request.user.email
            call_back_order.phone_number = phone_number_from_db
            call_back_order.comment = (
                form_data["comment"]
                + "\nПредпочитаемый способ связи: "
                + form_data["preferred_communication_method"]
            )
        else:
            call_back_order.name = form_data["name"]
            call_back_order.email = form_data["email"]
            call_back_order.phone_number = form_data["phone_number"]
            call_back_order.comment = (
                form_data["comment"]
                + "\nПредпочитаемый способ связи: "
                + form_data["preferred_communication_method"]
            )
        call_back_order.timestamp = datetime.now()
        call_back_order.save()
        # сохраняется заявка на обратный
        form = (
            CallBackOrderForAuthorizedUsers()
            if user_is_authorized
            else CallBackOrderForUnauthorizedUsers()
        )
    context_data = {
        "form": form,
        "title": "О нас",
    }

    return render(request, "main_app/about.html", context=context_data)

templates/main_app/about.html
{% extends "main_app/base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block body_title %}{{ title }} | Контакты{% endblock %}

{% block body_content %}
    <div class="container marketing">
        <hr class="featurette-divider">
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">Способы связаться с нами. <span class="text-muted">А также местоположение на карте.</span></h2>
              <p class="lead my-4">Адрес сборки и производства мебели: ул. Нансена, 98, г. Ростов-на-Дону.</p>
              <ul class="navbar-nav py-4">
                <li class="nav-item nav-link">
                    <a href="tel:79515132537" class="nav-item nav-link">
                        <p class="h5"><i class="fa-solid fa-phone"></i> +7 951-513-25-37</p>
                    </a>
                </li>
                <li class="nav-item nav-link">
                    <div class="col nav-item nav-link">
                        <a href="mailto:astra_tilda@mail.ru" class="nav-item nav-link">
                            <p class="h5"><i class="fa-solid fa-envelope"></i> astra_tilda@mail.ru</p>
                        </a>
                    </div>
                </li>
                <li class="nav-item nav-link">
                    <div class="col nav-item nav-link">
                        <a href="https://t.me/TacitKilgor" class="nav-item nav-link">
                            <p class="h5"><i class="fa-brands fa-telegram"></i> Написать нам в Telegram</p>
                        </a>
                    </div>
                </li>
            </ul>
          </div>
          <div class="col-md-5">
              <iframe class="rounded-3" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1610.5224724911866!2d39.69509420482027!3d47.2446512250869!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40e3b850a59ce1a7%3A0x4e892e7c8a6270e3!2z0YPQuy4g0J3QsNC90YHQtdC90LAsIDkyLCDQoNC-0YHRgtC-0LIt0L3QsC3QlNC-0L3Rgywg0KDQvtGB0YLQvtCy0YHQutCw0Y8g0L7QsdC7LiwgMzQ0MDEy!5e0!3m2!1sru!2sru!4v1669144640824!5m2!1sru!2sru" width="500" height="500" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        </div>
      </div>
      <hr class="py-2">
      <p id="calbackform" class="display-5 w-75 m-auto my-5 text-center">Если не нашли на сайте того, что Вам нужно, оставьте заявку на обратную связь с помощью формы ниже. Мы обязательно ответим Вам!</p>
    {% if not request.user.is_authenticated %}

        <div class="form-signin w-75 m-auto">
            <form action="{% url "about" %}" method="post">
                <div class="form-floating">
                    {% csrf_token %}
                    {{ form|crispy }}
                </div>
                <div class="container m-3 text-center">
                    <button class="btn btn-dark my-3 w-50" type="submit">Отправить заявку</button>
                </div>
            </form>
        </div>
    {% else %}
        <p class="h3 w-50 m-auto my-3 text-center text-danger">Контактные данные вводить не нужно! <br> Мы возьмем их из указанных в Вашей учетной записи!</p>
        <div class="form-signin w-75 m-auto">
            <form action="{% url "about" %}" method="post">
                <div class="form-floating">
                    {% csrf_token %}
                    {{ form.comment|as_crispy_field }}
                    {{ form.preferred_communication_method|as_crispy_field }}
                </div>
                <div class="container m-3 text-center">
                    <button class="btn btn-dark my-3 w-50" type="submit">Отправить заявку</button>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

templates/main_app/base.html
<!doctype html>
{% load static %}
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="{% static "main_app/css/bootstrap.css" %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static "fontawesomefree/css/fontawesome.css" %}">
        <link rel="stylesheet" href="{% static "fontawesomefree/css/brands.css" %}">
        <link rel="stylesheet" href="{% static "fontawesomefree/css/solid.css" %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <title>Интернет-магазин фурнитуры АСТРА | {{ title }}</title>
        <style>
            html{
                font-family: Monserrat, sans-serif;
            }
        </style>
        {% block head_content %}{% endblock %}
    </head>
    <body class="bg-white">
        <header>
            <nav class="navbar navbar-dark bg-dark fixed-top">
              <div class="container">
                  <a class="navbar-brand" href="{% url "main_page" %}">
                      <i class="fa-solid fa-bahai"></i> АСТРА</a>
                  {% if request.user.is_authenticated and cart.get_total_quantities > 0 %}
                      <div class="cart"><a class="text-white" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-basket-shopping"></i> Корзина ({{ cart.get_total_quantities }} шт. на {{ cart.get_total_price }}p.)</a></div>
                  {% else %}
                      <div class="cart"><a class="text-white" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-basket-shopping"></i> Корзина (пусто)</a></div>
                  {% endif %}
                <button class="navbar-toggler bg-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                  <div class="offcanvas-header bg-dark">
                    <a class="navbar-brand" href="{% url "main_page" %}">
                      <i class="fa-solid fa-bahai"></i> АСТРА</a>
                    <button type="button" class="btn-close btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                  </div>
                  <div class="offcanvas-body bg-dark">
                    <ul class="navbar-nav text-white">
                        <div class="container">
                                 <li class="nav-item text-white">
                                    <a class="nav-link" href="{% url "main_page" %}"><p class="h4"><i class="fa-solid fa-house"></i> Главная</p></a>
                                </li>
                                 <li class="nav-item text-white">
                                    <a class="nav-link" href="{% url "catalog" %}"><p class="h4"><i class="fa-solid fa-list"></i> Каталог товаров</p></a>
                                </li>
                                 <li class="nav-item text-white">
                                    <a class="nav-link" href="{% url "about" %}"><p class="h4"><i class="fa-solid fa-info-circle"></i> О нас</p></a>
                                </li>
                            {% if request.user.is_authenticated %}
                                <div class="py-4">
                                    <a class="nav-link" href="{% url "user_cabinet" %}"><p class="h4"><i class="fa-solid fa-user"></i> {{ request.user.username.capitalize }}</p></a>
                                    <a class="nav-link" href="{% url "logout" %}"><p class="h4"><i class="fa-solid fa-right-from-bracket"></i> Выйти </p></a>
                                </div>
                            {% else %}
                                <a class="nav-link py-4" href="{% url "login" %}"><p class="h4"><i class="fa-solid fa-user"></i> Личный кабинет</p></a>
                            {% endif %}
                        </div>
                    </ul>
                  </div>
                  <div class="container py-4">
                      <div class="container">
                          <hr>
                          <ul class="navbar-nav">
                              <li class="nav-item text-white">
                                  <a href="mailto:astra_tilda@mail.ru" class="nav-item text-white nav-link">
                                      <p class="h5"><i class="fa-solid fa-envelope"></i> astra_tilda@mail.ru</p>
                                  </a>
                              </li>
                              <li class="nav-item text-white">
                                  <a href="tel:79515132537" class="nav-item text-white nav-link">
                                      <p class="h5"><i class="fa-solid fa-phone"></i> +7 951-513-25-37</p>
                                  </a>
                              </li>
                              <li class="nav-item text-white nav-link">
                                  <a href="https://t.me/TacitKilgor" class="nav-item text-white nav-link">
                                      <p class="h5"><i class="fa-brands fa-telegram"></i> Написать нам в Telegram</p>
                                  </a>
                              </li>
                          </ul>
                      </div>
                  </div>
                </div>
              </div>
            </nav>
        </header>
        <main style="height: 100%" >
            <div class="container gy-5" style="margin-top: 4rem; margin-bottom: 4rem">
                <p class="display-2 my-5">{% block body_title %}{% endblock %}</p>
                {% block body_content %}{% endblock %}
            </div>
        </main>
        <footer class="footer mt-auto py-3 text-center text-bg-dark bg-dark">
            <div class="container">
                <div class="container">
                    <div class="row">
                        <div class="col nav-item text-white nav-link">
                            <a href="tel:79515132537" class="nav-item text-white nav-link">
                                <p class="h5"><i class="fa-solid fa-phone"></i> +7 951-513-25-37</p>
                            </a>
                        </div>
                        <div class="col nav-item text-white nav-link">
                            <a href="mailto:astra_tilda@mail.ru" class="nav-item text-white nav-link">
                                <p class="h5"><i class="fa-solid fa-envelope"></i> astra_tilda@mail.ru</p>
                            </a>
                        </div>
                        <div class="col nav-item text-white nav-link">
                            <a href="https://t.me/TacitKilgor" class="nav-item text-white nav-link">
                                <p class="h5"><i class="fa-brands fa-telegram"></i> Написать нам в Telegram</p>
                            </a>
                        </div>
                    </div>
                    <span class="my-3">АСТРА 2022 <i class="fa-copyright fa-regular"></i></span>
                </div>
            </div>
        </footer>
    </body>
</html>

templates/main_app/catalog.html
{% extends "main_app/base.html" %}

{% block body_title %}Каталог товаров по категориям{% endblock %}

{% block body_content %}
    <div class="container">
        <div class="album">
            <div class="container d-flex justify-content-center mt-50 mb-50">
            {% if productcategory_list%}
                 <div class="row flex-column">
                    <div class="col rounded-3">
                        {% for productcategory in productcategory_list %}
                            <div class="row py-4">
                                <div class="col-lg-8 mx-auto">
                                    <ul class="list-group shadow">
                                        <li class="list-group-item row rounded-3 bg-white">
                                            <img class="col" src="{{ productcategory.image.url }}" alt="{{ productcategory.name.lower.split }}-img">
                                            <div class="media align-items-lg-center flex-column flex-lg-row col p-3">
                                                <div class="media-body order-2 order-lg-1">
                                                    <a class="text-primary" href="{% url "category" category_id=productcategory.id %}"><p class="h4 mt-0 mb-2">{{ productcategory.name.capitalize }}</p></a>
                                                    <p class="font-italic text-muted mb-0 small">{{ productcategory.description.capitalize|truncatechars:55 }}</p>
                                                    <div class="d-flex align-items-center justify-content-between mt-1">
                                                        <h6 class="font-weight-bold my-2">Позиций в категории: {{productcategory.product_set.count}} шт.</h6>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <p class="display-4 text-center">Здесь ничего нет! Перезагрузите страницу и, если это не помогло,
                    <a class="text-primary" href="{% url "about" %}">свяжитесь с нами</a>!</p>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/main_app/category_single.html
{% extends "main_app/base.html" %}
{% load crispy_forms_filters %}

{% block body_title %}Товары категории «{{ title }}» {% endblock %}

{% block body_content %}
    {% if not request.user.is_authenticated %}<p class="display-6">Чтобы оформить заказ, зарегистрируйтесь, перейдя в <a class="text-primary" href="{% url "login" %}">ЛИЧНЫЙ КАБИНЕТ</a>. <br>Чтобы связаться с нами, перейдите в раздел <a class="text-primary" href="{% url "about" %}">О НАС</a> (оба раздела есть в боковом меню).</p>{% endif %}
    {% if product_list %}
        <div class="row flex-column">
            <div class="col rounded-3">
                {% for product in product_list %}
                    <div class="row py-4">
                        <div class="col-lg-8 mx-auto">
                            <ul class="list-group shadow">
                                <li class="list-group-item row rounded-3 bg-white">
                                    <img class="col" src="{{ product.image.url }}" alt="{{ product.name.lower.split }}-img">
                                    <div class="media align-items-lg-center flex-column flex-lg-row col p-3">
                                        <div class="media-body order-2 order-lg-1">
                                            <a class="text-primary" href="{% url "product" product_id=product.id %}"><p class="h4 mt-0 mb-2">{{ product.name.capitalize }}</p></a>
                                            <p class="font-italic text-muted mb-0 small">{{ product.description.capitalize|truncatechars:150 }}</p>
                                            <div class="d-flex align-items-center justify-content-between mt-1">
                                                <h6 class="font-weight-bold my-2">ЦЕНА: {{product.price}} ₽/шт.</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <a class="text-primary" href="{% url "catalog" %}">В каталог</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
    {% else %}
                <p class="display-5">В категории «{{ title }}» товар временно отсутствует. Следите за обновлениями!</p>
    {% endif %}
            </div>
        </div>
{% endblock %}

templates/main_app/main_page.html
{% extends "main_app/base.html" %}

{% block head_content %}

{% endblock %}

{% block body_content %}
    <div class="container py-4">
        <div class="p-5 mb-4 bg-dark rounded-3 shadow">
          <div class="container-fluid py-5 text-white">
            <p class="display-2 fw-bold"><i class="fa-solid fa-bahai"></i> АСТРА</a></p>
            <p class="display-4 fw-bold">Индивидуальные заказы мебели для дома </p>
            <p class="col-md-8 fs-4">АСТРА — небольшая независимая студия, базирующаяся в городе Ростове-на-Дону.</p>
            <a class="btn w-25 btn-outline-light btn-lg" type="button" href="{% url "catalog" %}">Каталог</a>
          </div>
        </div>
        <div class="row align-items-md-stretch gy-4">
          <div class="col-md-6 gy-4">
            <div class="h-100 p-5 rounded-3 bg-light shadow">
              <h1 class="display-6">Шкафы</h1>
              <p class="fs-5">И не только они. Мы работаем с разными стилями и функционалом, подбираем для каждого клиента уникальные решения.</p>
              <a class="btn btn-outline-dark" href="{% url "catalog" %}">Перейти в каталог товаров</a>
            </div>
          </div>
          <div class="col-md-6 gy-4">
            <div class="h-100 p-5 bg-light border rounded-3 shadow">
              <h1 class="display-6">Астра?</h1>
              <p class="fs-5">Что означает название компании?  <br> Мебель должна создавать <strong>атмосферу</strong> — это важно, чтобы вымогли чувствовать себя комфортно дома после тяжёлого дня.
              Мебель должна быть <strong>стильной, тактильной, родной и аккуратной</strong>.</p>
              <a class="btn btn-outline-dark" href="{% url "about" %}">Информация о нас</a>
              <a class="btn btn-outline-dark" href="{% url "about" %}#calbackform">Заказать обратный звонок</a>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

templates/main_app/product_single.html
{% extends "main_app/base.html" %}
{% load crispy_forms_filters %}


{% block body_title %}{{ title }}{% endblock %}

{% block body_content %}
    {% if object %}
        <div class="card text-center bg-white shadow">
            <img class="rounded-1" src="{{ object.image.url }}" alt="">
          <div class="card-body container py-3">
            <p class="h2">{{ object.name.capitalize }}</p>
            <p class="card-text">{{ object.description}}</p>
            <div class="d-flex justify-content-between justify-content-center align-items-center">
                <div class="row">
                {% if request.user.is_authenticated %}
                    <form class="w-25 col" action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ add_to_cart_form.quantity }}
                        {{ add_to_cart_form.update }}
                        <input class="btn btn-dark" type="submit" value="В корзину">
                        {% csrf_token %}
                     </form>
                {% endif %}
                    <div class="col" style="width: 15rem">
                        <a class="text-primary" href="{% url "category" category_id=object.category_id %}">В категорию «{{ product.category.name.capitalize }}»</a>
                    </div>
                </div>
                <small class="text-muted col">ЦЕНА: {{ product.price }} ₽/шт.</small>
            </div>
          </div>
    {% else %}
        Упс, что-то пошло не так! Перейдите на главную и обновите страницу.
    {% endif %}
{% endblock %}